name: expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <4.0.0'  # Updated SDK version

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1  # Use only one version of sqflite
  path: ^1.8.0     # Properly indented
  fl_chart: ^0.70.2
  sqflite_common_ffi: ^2.0.0
  sqflite_common_ffi_web: ^1.0.0
  logger: ^2.5.0
  path_provider: ^2.1.1
  pdf: ^3.10.0  # For PDF export
  csv: ^6.0.0   # For CSV export
  file_picker: ^9.0.0  # Add this line
  dynamic_color: ^1.6.9
  google_fonts: ^6.1.0
  flex_color_scheme: ^7.3.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  google_mlkit_text_recognition: ^0.11.0
  permission_handler: ^11.3.0
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  intl: ^0.18.1
  camera: ^0.10.5+5
  share_plus: ^7.0.0 # Use the latest version

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf