name: Build iOS App
on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4  # Updated to latest version
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'  # Updated to a more recent Ruby version
        
    - name: Install dependencies
      run: |
        gem install xcpretty
        
    - name: Create export options plist
      run: |
        cat > exportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>compileBitcode</key>
            <false/>
            <key>teamID</key>
            <string>YOUR_TEAM_ID</string>
            <key>provisioningProfiles</key>
            <dict>
                <key>com.yourcompany.yourapp</key>
                <string>Your Provisioning Profile Name</string>
            </dict>
        </dict>
        </plist>
        EOF
        
    - name: Build iOS app
      run: |
        xcodebuild clean archive \
        -project YourProject.xcodeproj \
        -scheme YourScheme \
        -configuration Release \
        -archivePath $GITHUB_WORKSPACE/build/YourApp.xcarchive \
        -sdk iphoneos \
        ONLY_ACTIVE_ARCH=NO
        
    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
        -archivePath $GITHUB_WORKSPACE/build/YourApp.xcarchive \
        -exportOptionsPlist exportOptions.plist \
        -exportPath $GITHUB_WORKSPACE/build
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # Updated to latest version
      with:
        name: YourAppIPA
        path: $GITHUB_WORKSPACE/build/*.ipa
