name: Flutter iOS Local Build

on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches: [ nightly_dev ]
  pull_request:
    branches: [ nightly_dev ]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'
        channel: 'stable'

    - name: Install Flutter dependencies
      run: |
        flutter pub get
        flutter clean

    - name: Build iOS App
      run: |
        flutter build ios --release --no-codesign

    - name: Create unsigned IPA
      run: |
        mkdir -p build/ios/ipa
        cd build/ios/iphoneos
        mkdir Payload
        cp -R Runner.app Payload/
        zip -r ../ipa/unsigned.ipa Payload
        cd ../../..

    - name: Upload Unsigned IPA
      uses: actions/upload-artifact@v4
      with:
        name: unsigned-ios-app
        path: build/ios/ipa/*.ipa
        retention-days: 5